<<<<<<< HEAD
spring.datasource.url=jdbc:mysql://localhost:3306/petcare_db
spring.datasource.username=root
spring.datasource.password=Kavi@2002
=======
spring.application.name=Pet_Boarding_And_Daycare_System
spring.datasource.url=jdbc:mysql://localhost:3306/petcare_db
spring.datasource.username=root
spring.datasource.password=madara2002
>>>>>>> main
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
